namespace SpriteKind {
    export const boss = SpriteKind.create()
    export const Boss1 = SpriteKind.create()
    export const complete = SpriteKind.create()
    export const Treasure = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.vy == 0) {
        mySprite.vy = -200
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Treasure, function (sprite, otherSprite) {
    DialogMode = true
    game.showLongText("Which superhero is known as the Warrior Princess of the Amazons?", DialogLayout.Bottom)
    story.showPlayerChoices("Black Widow ", "Wonder Woman", "Captain Marvel")
    if (story.checkLastAnswer("Black Widow ")) {
        music.play(music.melodyPlayable(music.wawawawaa), music.PlaybackMode.UntilDone)
        info.changeLifeBy(0)
        treasure.setKind(SpriteKind.complete)
        sprites.destroy(treasure, effects.confetti, 500)
    } else if (story.checkLastAnswer("Wonder Woman")) {
        music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
        info.changeLifeBy(1)
        treasure.setKind(SpriteKind.complete)
        sprites.destroy(treasure, effects.confetti, 500)
    } else if (story.checkLastAnswer("Captain Marvel")) {
        music.play(music.melodyPlayable(music.wawawawaa), music.PlaybackMode.UntilDone)
        info.changeLifeBy(0)
        treasure.setKind(SpriteKind.complete)
        sprites.destroy(treasure, effects.confetti, 500)
    } else {
    	
    }
    DialogMode = false
    pause(100)
})
function changeLevel (num: number) {
    if (num == 1) {
        tiles.setCurrentTilemap(tilemap`level4`)
    } else if (num == 2) {
        tiles.setCurrentTilemap(tilemap`level4`)
    } else if (num == 3) {
        tiles.setCurrentTilemap(tilemap`level1`)
        info.setLife(3)
        boss1()
        treasure = sprites.create(img`
            . . b b b b b b b b b b b b . . 
            . b e 4 4 4 4 4 4 4 4 4 4 e b . 
            b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
            b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
            b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
            b e e 4 4 4 4 4 4 4 4 4 4 e e b 
            b e e e e e e e e e e e e e e b 
            b e e e e e e e e e e e e e e b 
            b b b b b b b d d b b b b b b b 
            c b b b b b b c c b b b b b b c 
            c c c c c c b c c b c c c c c c 
            b e e e e e c b b c e e e e e b 
            b e e e e e e e e e e e e e e b 
            b c e e e e e e e e e e e e c b 
            b b b b b b b b b b b b b b b b 
            . b b . . . . . . . . . . b b . 
            `, SpriteKind.Treasure)
        tiles.placeOnTile(treasure, tiles.getTileLocation(0, 1))
    }
    tiles.placeOnRandomTile(mySprite, assets.tile`myTile`)
    tiles.setTileAt(mySprite.tilemapLocation(), assets.tile`transparency16`)
}
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    sprites.destroy(MyBoss, effects.disintegrate, 500)
    sprites.destroy(statusbar)
    BossAlive = false
    if (info.life() == 3) {
        info.changeScoreBy(20)
    } else if (info.life() == 2) {
        info.changeScoreBy(15)
    } else if (info.life() == 1) {
        info.changeScoreBy(10)
    } else {
        info.changeScoreBy(25)
    }
    game.setGameOverScoringType(game.ScoringType.HighScore)
})
function boss1 () {
    MyBoss = sprites.create(img`
        ....fffffffffff.........
        ...f33333533333f........
        ...f35333533353f........
        ..f3355535355533f.......
        ..f3335555555333f.......
        ..f3355555555533f.......
        ..f35bbbbbbbbb53f.......
        ..f35bf1bbbf1b53f.......
        ...f5bffbbbffb5f........
        ...f5bbbbbbbbb5f........
        ..f5f5bbbbbbb5f5f.......
        .f555fbbbbbbbf555f......
        .ff555fffffff555ff......
        ...f33555555533f........
        ..f33f3355533f33ff......
        .f555f3335333f5555f.....
        .f55ff5555555ffe73f.....
        ..ff.f5535355f.f59f.....
        ....ff3335333ff.ff......
        ....f333fff333f.........
        ....f55f...f55f.........
        ...f555f...f555f........
        ...fffff...fffff........
        ........................
        `, SpriteKind.Boss1)
    MyBoss.setScale(2, ScaleAnchor.Middle)
    MyBoss.ay = 350
    tiles.placeOnTile(MyBoss, tiles.getTileLocation(11, 8))
    BossAlive = true
    statusbar = statusbars.create(140, 10, StatusBarKind.EnemyHealth)
    statusbar.positionDirection(CollisionDirection.Bottom)
    statusbar.setOffsetPadding(0, 5)
    statusbar.setColor(3, 12, 5)
    statusbar.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
    statusbar.setBarBorder(2, 15)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Boss1, function (sprite2, otherSprite2) {
    if (mySprite.vy > 0 && mySprite.y < MyBoss.y) {
        game.setGameOverEffect(false, effects.blizzard)
        mySprite.vy = -70
        statusbar.value += -10
    } else {
        info.changeLifeBy(-1)
        statusbar.value += 10
    }
    pause(1000)
})
let BossAlive = false
let statusbar: StatusBarSprite = null
let MyBoss: Sprite = null
let treasure: Sprite = null
let DialogMode = false
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................
    ........................
    .....3.3.......3.3......
    ......3.........3.......
    .....3.3fffffff3.3......
    ......fa22aa22aaf.......
    ......f222aa222af.......
    ......f22122122af.......
    ......f33222233af.......
    ......fa22ff22aaf.......
    ......fa222222aaf.......
    ...fff..fffffff.........
    ...ffaffaaaaaaaf........
    ....fff2fa99aaf2f.......
    .......ffaaaaaffaf......
    ........ffaffaf.aaf.....
    .........ff.fff.........
    .........22.2b2.........
    .........33.3b3.........
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
DialogMode = false
scene.cameraFollowSprite(mySprite)
mySprite.ay = 380
changeLevel(3)
game.onUpdate(function () {
    if (BossAlive) {
        if (mySprite.x + 30 < MyBoss.x) {
            MyBoss.vx = -20
            MyBoss.setImage(img`
                ...fffffffffff..........
                ..f88888588888f.........
                ..f85888588858f.........
                .f8855585855588f........
                .f8885555555888f........
                .f8855555555588f........
                .f85bbbbbbbbb58f........
                .f85bf1bbbf1b58f........
                ..f5bffbbbffb5f.........
                ..f5bbbbbbbbb5f.........
                .f5f5bbbbbbb5f5f........
                f555fbbbbbbbf555f.......
                ff555fffffff555ff.......
                ..f88555555588f.........
                .f88f8855588f88ff.......
                f555f8885888f5555f......
                f55ff5555555ffe73f......
                .ff.f5585855f.f59f......
                ...ff8885888ff.ff.......
                ...f888fff888f..........
                ...f55f...f55f..........
                ..f555f...f555f.........
                ..fffff...fffff.........
                ........................
                `)
        } else if (mySprite.x - 30 > MyBoss.x) {
            MyBoss.vx = 20
            MyBoss.setImage(img`
                ...fffffffffff..........
                ..f88888588888f.........
                ..f85888588858f.........
                .f8855585855588f........
                .f8885555555888f........
                .f8855555555588f........
                .f85bbbbbbbbb58f........
                .f85bf1bbbf1b58f........
                ..f5bffbbbffb5f.........
                ..f5bbbbbbbbb5f.........
                .f5f5bbbbbbb5f5f........
                f555fbbbbbbbf555f.......
                ff555fffffff555ff.......
                ..f88555555588f.........
                .f88f8855588f88ff.......
                f555f8885888f5555f......
                f55ff5555555ffe73f......
                .ff.f5585855f.f59f......
                ...ff8885888ff.ff.......
                ...f888fff888f..........
                ...f55f...f55f..........
                ..f555f...f555f.........
                ..fffff...fffff.........
                ........................
                `)
        } else {
            MyBoss.vx = 0
        }
    }
})
game.onUpdate(function () {
    MyBoss.setImage(img`
        ....fffffffffff.........
        ...f33333933333f........
        ...f39333933393f........
        ..f3399939399933f.......
        ..f3339999999333f.......
        ..f3399999999933f.......
        ..f39bbbbbbbbb93f.......
        ..f39bf1bbbf1b93f.......
        ...f9bffbbbffb9f........
        ...f93bbbbbbb39f........
        ..f9f9bbfffbb9f9f.......
        .f999fbbbbbbbf999f......
        .ff999fffffff999ff......
        ...f33999999933f........
        ..f33f3399933f33ff......
        .f999f3339333f5999f.....
        .f99ff9999999ffe73f.....
        ..ff.f9939399f.f59f.....
        ....ff3339333ff.ff......
        ....f333fff333f.........
        ....f99f...f99f.........
        ...f999f...f999f........
        ...fffff...fffff........
        ........................
        `)
})
forever(function () {
    if (DialogMode == false) {
        controller.moveSprite(mySprite, 100, 0)
    } else if (DialogMode == true) {
        controller.moveSprite(mySprite, 0, 0)
    } else {
    	
    }
})
