@namespace
class SpriteKind:
    boss = SpriteKind.create()
    Boss1 = SpriteKind.create()
    complete = SpriteKind.create()
    Treasure = SpriteKind.create()

def on_a_pressed():
    if mySprite.vy == 0:
        mySprite.vy = -200
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_on_overlap(sprite, otherSprite):
    global DialogMode
    DialogMode = True
    game.show_long_text("Which superhero is known as the Warrior Princess of the Amazons?",
        DialogLayout.BOTTOM)
    story.show_player_choices("Black Widow ", "Wonder Woman", "Captain Marvel")
    if story.check_last_answer("Black Widow "):
        music.play(music.melody_playable(music.wawawawaa),
            music.PlaybackMode.UNTIL_DONE)
        info.change_life_by(0)
        treasure.set_kind(SpriteKind.complete)
        sprites.destroy(treasure, effects.confetti, 500)
    elif story.check_last_answer("Wonder Woman"):
        music.play(music.melody_playable(music.ba_ding),
            music.PlaybackMode.UNTIL_DONE)
        info.change_life_by(1)
        treasure.set_kind(SpriteKind.complete)
        sprites.destroy(treasure, effects.confetti, 500)
    elif story.check_last_answer("Captain Marvel"):
        music.play(music.melody_playable(music.wawawawaa),
            music.PlaybackMode.UNTIL_DONE)
        info.change_life_by(0)
        treasure.set_kind(SpriteKind.complete)
        sprites.destroy(treasure, effects.confetti, 500)
    else:
        pass
    DialogMode = False
    pause(100)
sprites.on_overlap(SpriteKind.player, SpriteKind.Treasure, on_on_overlap)

def changeLevel(num: number):
    global treasure
    if num == 1:
        tiles.set_current_tilemap(tilemap("""
            level4
        """))
    elif num == 2:
        tiles.set_current_tilemap(tilemap("""
            level4
        """))
    elif num == 3:
        tiles.set_current_tilemap(tilemap("""
            level1
        """))
        info.set_life(3)
        boss1()
        treasure = sprites.create(img("""
                . . b b b b b b b b b b b b . . 
                            . b e 4 4 4 4 4 4 4 4 4 4 e b . 
                            b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
                            b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
                            b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
                            b e e 4 4 4 4 4 4 4 4 4 4 e e b 
                            b e e e e e e e e e e e e e e b 
                            b e e e e e e e e e e e e e e b 
                            b b b b b b b d d b b b b b b b 
                            c b b b b b b c c b b b b b b c 
                            c c c c c c b c c b c c c c c c 
                            b e e e e e c b b c e e e e e b 
                            b e e e e e e e e e e e e e e b 
                            b c e e e e e e e e e e e e c b 
                            b b b b b b b b b b b b b b b b 
                            . b b . . . . . . . . . . b b .
            """),
            SpriteKind.Treasure)
        tiles.place_on_tile(treasure, tiles.get_tile_location(0, 1))
    tiles.place_on_random_tile(mySprite, assets.tile("""
        myTile
    """))
    tiles.set_tile_at(mySprite.tilemap_location(),
        assets.tile("""
            transparency16
        """))

def on_on_zero(status):
    global BossAlive
    sprites.destroy(MyBoss, effects.disintegrate, 500)
    sprites.destroy(statusbar)
    BossAlive = False
    if info.life() == 3:
        info.change_score_by(20)
    elif info.life() == 2:
        info.change_score_by(15)
    elif info.life() == 1:
        info.change_score_by(10)
    else:
        info.change_score_by(25)
    game.set_game_over_scoring_type(game.ScoringType.HIGH_SCORE)
statusbars.on_zero(StatusBarKind.enemy_health, on_on_zero)

def boss1():
    global MyBoss, BossAlive, statusbar
    MyBoss = sprites.create(img("""
            ....fffffffffff.........
                    ...f33333533333f........
                    ...f35333533353f........
                    ..f3355535355533f.......
                    ..f3335555555333f.......
                    ..f3355555555533f.......
                    ..f35bbbbbbbbb53f.......
                    ..f35bf1bbbf1b53f.......
                    ...f5bffbbbffb5f........
                    ...f5bbbbbbbbb5f........
                    ..f5f5bbbbbbb5f5f.......
                    .f555fbbbbbbbf555f......
                    .ff555fffffff555ff......
                    ...f33555555533f........
                    ..f33f3355533f33ff......
                    .f555f3335333f5555f.....
                    .f55ff5555555ffe73f.....
                    ..ff.f5535355f.f59f.....
                    ....ff3335333ff.ff......
                    ....f333fff333f.........
                    ....f55f...f55f.........
                    ...f555f...f555f........
                    ...fffff...fffff........
                    ........................
        """),
        SpriteKind.Boss1)
    MyBoss.set_scale(2, ScaleAnchor.MIDDLE)
    MyBoss.ay = 350
    tiles.place_on_tile(MyBoss, tiles.get_tile_location(11, 8))
    BossAlive = True
    statusbar = statusbars.create(140, 10, StatusBarKind.enemy_health)
    statusbar.position_direction(CollisionDirection.BOTTOM)
    statusbar.set_offset_padding(0, 5)
    statusbar.set_color(3, 12, 5)
    statusbar.set_status_bar_flag(StatusBarFlag.SMOOTH_TRANSITION, True)
    statusbar.set_bar_border(2, 15)

def on_on_overlap2(sprite2, otherSprite2):
    if mySprite.vy > 0 and mySprite.y < MyBoss.y:
        game.set_game_over_effect(False, effects.blizzard)
        mySprite.vy = -70
        statusbar.value += -10
    else:
        info.change_life_by(-1)
        statusbar.value += 10
    pause(1000)
sprites.on_overlap(SpriteKind.player, SpriteKind.Boss1, on_on_overlap2)

BossAlive = False
statusbar: StatusBarSprite = None
MyBoss: Sprite = None
treasure: Sprite = None
DialogMode = False
mySprite: Sprite = None
mySprite = sprites.create(img("""
        ........................
            ........................
            .....3.3.......3.3......
            ......3.........3.......
            .....3.3fffffff3.3......
            ......fa22aa22aaf.......
            ......f222aa222af.......
            ......f22122122af.......
            ......f33222233af.......
            ......fa22ff22aaf.......
            ......fa222222aaf.......
            ...fff..fffffff.........
            ...ffaffaaaaaaaf........
            ....fff2fa99aaf2f.......
            .......ffaaaaaffaf......
            ........ffaffaf.aaf.....
            .........ff.fff.........
            .........22.2b2.........
            .........33.3b3.........
            ........................
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.player)
DialogMode = False
scene.camera_follow_sprite(mySprite)
mySprite.ay = 380
changeLevel(3)

def on_on_update():
    if BossAlive:
        if mySprite.x + 30 < MyBoss.x:
            MyBoss.vx = -20
            MyBoss.set_image(img("""
                ...fffffffffff..........
                                ..f88888588888f.........
                                ..f85888588858f.........
                                .f8855585855588f........
                                .f8885555555888f........
                                .f8855555555588f........
                                .f85bbbbbbbbb58f........
                                .f85bf1bbbf1b58f........
                                ..f5bffbbbffb5f.........
                                ..f5bbbbbbbbb5f.........
                                .f5f5bbbbbbb5f5f........
                                f555fbbbbbbbf555f.......
                                ff555fffffff555ff.......
                                ..f88555555588f.........
                                .f88f8855588f88ff.......
                                f555f8885888f5555f......
                                f55ff5555555ffe73f......
                                .ff.f5585855f.f59f......
                                ...ff8885888ff.ff.......
                                ...f888fff888f..........
                                ...f55f...f55f..........
                                ..f555f...f555f.........
                                ..fffff...fffff.........
                                ........................
            """))
        elif mySprite.x - 30 > MyBoss.x:
            MyBoss.vx = 20
            MyBoss.set_image(img("""
                ...fffffffffff..........
                                ..f88888588888f.........
                                ..f85888588858f.........
                                .f8855585855588f........
                                .f8885555555888f........
                                .f8855555555588f........
                                .f85bbbbbbbbb58f........
                                .f85bf1bbbf1b58f........
                                ..f5bffbbbffb5f.........
                                ..f5bbbbbbbbb5f.........
                                .f5f5bbbbbbb5f5f........
                                f555fbbbbbbbf555f.......
                                ff555fffffff555ff.......
                                ..f88555555588f.........
                                .f88f8855588f88ff.......
                                f555f8885888f5555f......
                                f55ff5555555ffe73f......
                                .ff.f5585855f.f59f......
                                ...ff8885888ff.ff.......
                                ...f888fff888f..........
                                ...f55f...f55f..........
                                ..f555f...f555f.........
                                ..fffff...fffff.........
                                ........................
            """))
        else:
            MyBoss.vx = 0
game.on_update(on_on_update)

def on_on_update2():
    MyBoss.set_image(img("""
        ....fffffffffff.........
                ...f33333933333f........
                ...f39333933393f........
                ..f3399939399933f.......
                ..f3339999999333f.......
                ..f3399999999933f.......
                ..f39bbbbbbbbb93f.......
                ..f39bf1bbbf1b93f.......
                ...f9bffbbbffb9f........
                ...f93bbbbbbb39f........
                ..f9f9bbfffbb9f9f.......
                .f999fbbbbbbbf999f......
                .ff999fffffff999ff......
                ...f33999999933f........
                ..f33f3399933f33ff......
                .f999f3339333f5999f.....
                .f99ff9999999ffe73f.....
                ..ff.f9939399f.f59f.....
                ....ff3339333ff.ff......
                ....f333fff333f.........
                ....f99f...f99f.........
                ...f999f...f999f........
                ...fffff...fffff........
                ........................
    """))
game.on_update(on_on_update2)

def on_forever():
    if DialogMode == False:
        controller.move_sprite(mySprite, 100, 0)
    elif DialogMode == True:
        controller.move_sprite(mySprite, 0, 0)
    else:
        pass
forever(on_forever)
